'use strict';

module.exports = (sequelize, DataTypes) => {
  const Event = sequelize.define('Event', {
    eventCode: { type: DataTypes.STRING, unique: true },
    title: { type: DataTypes.STRING, allowNull: false },
    organizer: { type: DataTypes.STRING },
    category: { type: DataTypes.STRING },
    venueName: { type: DataTypes.STRING },
    venueAddress: { type: DataTypes.STRING },
    venueMapLink: { type: DataTypes.STRING },
    priceAmount: { type: DataTypes.FLOAT, defaultValue: 0 },
    priceCurrency: { type: DataTypes.STRING, defaultValue: 'INR' },
    isEarlyBird: { type: DataTypes.BOOLEAN, defaultValue: false },
    capacityTotal: { type: DataTypes.INTEGER },
    capacityRemaining: { type: DataTypes.INTEGER },
    eventDate: { type: DataTypes.DATE },
    shortDescription: { type: DataTypes.TEXT },
    fullDescription: { type: DataTypes.TEXT },
    agenda: { type: DataTypes.JSON },
    prerequisites: { type: DataTypes.JSON },
    tags: { type: DataTypes.JSON },
    userId: { type: DataTypes.INTEGER },
    city: { type: DataTypes.STRING },
    state: { type: DataTypes.STRING },
    indoorOutdoor: { type: DataTypes.ENUM('indoor', 'outdoor') },
    numberOfGuests: { type: DataTypes.INTEGER },
    specialCategories: { type: DataTypes.JSON },
    guestList: { type: DataTypes.STRING },
    ticketType: { type: DataTypes.STRING },
    numberOfTickets: { type: DataTypes.INTEGER },
    budgetRange: { type: DataTypes.STRING },
    eventTimeStart: { type: DataTypes.STRING },
    eventTimeEnd: { type: DataTypes.STRING },
    eventDuration: { type: DataTypes.STRING },
    cateringRequired: { type: DataTypes.BOOLEAN, defaultValue: false },
    decorationServices: { type: DataTypes.BOOLEAN, defaultValue: false },
    photography: { type: DataTypes.BOOLEAN, defaultValue: false },
    musicDJ: { type: DataTypes.BOOLEAN, defaultValue: false },
    equipment: { type: DataTypes.JSON },
    customRequirements: { type: DataTypes.TEXT },
    accessibilityNeeds: { type: DataTypes.TEXT },
    dietaryRestrictions: { type: DataTypes.TEXT },
    paymentMethod: { type: DataTypes.ENUM('card', 'upi', 'cash') },
    advancePayment: { type: DataTypes.FLOAT },
    billingAddress: { type: DataTypes.TEXT },
    promoCode: { type: DataTypes.STRING },
    referralSource: { type: DataTypes.STRING },
    fileUpload: { type: DataTypes.STRING },
    isDeleted: { type: DataTypes.BOOLEAN, defaultValue: false },
    isActive: { type: DataTypes.BOOLEAN, defaultValue: true },
    deletedAt: { type: DataTypes.DATE, allowNull: true },
    registrationDeadline: { type: DataTypes.DATE, allowNull: true },
    visibleFrom: { type: DataTypes.DATE, allowNull: true },
    bookingOpenDate: { type: DataTypes.DATE, allowNull: true }
  });

  return Event;
}; 